# Generated by Django 3.0.3 on 2020-02-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='file_type',
            field=models.CharField(default='.mp3', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='song_title',
            field=models.CharField(default='song title', max_length=256),
            preserve_default=False,
        ),
    ]
